# Generated by Django 5.0.1 on 2024-02-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_item_quantity_alter_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(blank=True),
        ),
    ]
